name: BasketBall API
services:
  app:
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/basketball
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
  db:
    image: postgres:17-alpine
    restart: always
    container_name: db
    user: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: basketball
    ports:
      - '5432:5432'
    volumes:
      - db:/data/db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
volumes:
  db:
    driver:
      local